import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { ConvexAuthNextjsServerProvider } from "@convex-dev/auth/nextjs/server";
import ConvexClientProvider from "@/components/ConvexClientProvider";
import Image from "next/image";
import SignOutButton from "./signOutButton";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Convex + Next.js + ConvexAuth",
  description: "Generated by create convex",
  icons: {
    icon: "/convex.svg",
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ConvexAuthNextjsServerProvider>
      <html lang="en">
        <body
          className={`${geistSans.variable} ${geistMono.variable} antialiased`}
        >
          <ConvexClientProvider>
            <header className="sticky top-0 z-10 bg-background/80 backdrop-blur-md p-4 border-b border-slate-200 dark:border-slate-700 flex flex-row justify-between items-center shadow-sm">
              <div className="flex items-center gap-3">
                <div className="flex items-center gap-3">
                  <Image
                    src="/convex.svg"
                    alt="Convex Logo"
                    width={32}
                    height={32}
                  />
                  <div className="w-px h-8 bg-slate-300 dark:bg-slate-600"></div>
                  <Image
                    src="/nextjs-icon-light-background.svg"
                    alt="Next.js Logo"
                    width={32}
                    height={32}
                    className="dark:hidden"
                  />
                  <Image
                    src="/nextjs-icon-dark-background.svg"
                    alt="Next.js Logo"
                    width={32}
                    height={32}
                    className="hidden dark:block"
                  />
                </div>
                <h1 className="font-semibold text-slate-800 dark:text-slate-200">
                  Convex + Next.js + Convex Auth
                </h1>
              </div>
              <SignOutButton />
            </header>
            {children}
          </ConvexClientProvider>
        </body>
      </html>
    </ConvexAuthNextjsServerProvider>
  );
}
